### ISSUE TITLE
Clarrification about steps 9 and 10 from D2R tutorial.

### ISSUE THREAD

**Issue by bpcommunity** [borntohonk/SigPatches#4]
Could you provide some clarification please?

Item 9:
"Use the knowledge gained, Offset, size 4, NOP (translates to 1b 9A 70 00 04 1F 20 03 D5)".

I'm trying to figure out how do you calculate the 256 bytes change in the memory address. When I use the Ghidra, I find the position on D2R, but don't saw the logic behind the increase on the address. The 4 bytes of the NOP instruction is the "tip"?

Item 10:
How do you calculate the number related to the name of the .ips file?

My version of the patch does not work on the last update, but I was able to follow, almost, all parts of the tutorial. I use your Python code to generate the .ips (saw that you get the name of the .ips from there, but don't get the logic behind).

Thanks for your tutorials and code, I learn a lot reading them. Very good material.

**Comment by borntohonk** [comment]
> Could you provide some clarification please?
> 
> Item 9: "Use the knowledge gained, Offset, size 4, NOP (translates to 1b 9A 70 00 04 1F 20 03 D5)".
> 
> I'm trying to figure out how do you calculate the 256 bytes change in the memory address. When I use the Ghidra, I find the position on D2R, but don't saw the logic behind the increase on the address. The 4 bytes of the NOP instruction is the "tip"?
> 
> Item 10: How do you calculate the number related to the name of the .ips file?
> 
> My version of the patch does not work on the last update, but I was able to follow, almost, all parts of the tutorial. I use your Python code to generate the .ips (saw that you get the name of the .ips from there, but don't get the logic behind).
> 
> Thanks for your tutorials and code, I learn a lot reading them. Very good material.

Well the file name in the .ips files (very explicitly for exefs files, not kip patches), are just a representation of the buildid, which can be found either with hactool using hactool -t nso0, or 0x14 length from 0x40 in an uncompressed nso0 (the file called "main")

This following example is one i produced right now using these commands.

```
hactool -t pfs0 "Diablo II Resurrected[0100726014352800][US][v655360].nsp" --outdir temp
hactool -t nca temp/be4a9ceca577364742d4e3e6cbbc1670.nca --titlekey=259996817E2F93DB8B2A0B383175439D --exefsdir exefs
hactool -t nso0 exefs/main --uncompressed=main

Output:
NSO0:
    Build Id:                       DCEDBABB85CB423777F7D044BAEC91D5672A5BA8000000000000000000000000
    Sections:
        .text:                      00000000-018cf000
        .rodata:                    018cf000-01d5d000
        .rwdata:                    01d5d000-01e30820
        .bss:                       01e30820-02f45000
Done!
python3 d2r_patch.py

Output:
d2r build-id: DCEDBABB85CB423777F7D044BAEC91D5672A5BA8
d2r offset and patch at: 1C670800041F2003D5
d2r cheat string: 04000000 001C6608 D503201F
```

**Comment by borntohonk** [comment]
I guess in hindsight maybe I should explain how to get the buildid in the guide too, i as that's simple enough

**Comment by borntohonk** [comment]
on linux you could use `xxd -c 20 -l 0x14 -s 0x40- -g 20 main` 
which should output 
`00000040: dcedbabb85cb423777f7d044baec91d5672a5ba8  ......B7w..D....g*[.`

or a hexadecimal editor like HxD / whichever hex editor you prefer, if you do not use hactool to get the buildid, or the python script which outputs the buildid for you.

**Comment by borntohonk** [comment]
https://developer.arm.com/documentation/dui0489/c/arm-and-thumb-instructions/miscellaneous-instructions/nop#:~:text=Usage,necessarily%20a%20time%2Dconsuming%20NOP%20.

the NOP is an arm instruction 

I think that should answer your questions, unless you wonder about anything else.
@bpcommunity

**Comment by borntohonk** [comment]
https://github.com/borntohonk/SigPatches/commit/3e5d20fbb87e7e28662d86312809f651813f4ac9

**Comment by bpcommunity** [comment]
Perfect, solved my doubts. Thanks!
