### ISSUE TITLE
usb3.0 patch     thanks

### ISSUE THREAD

**Issue by lsp199308** [borntohonk/SigPatches#5]
can you add usb3.0 patch? ams since hos13, usb3.0 is not working, i found that by patching i can turn on usb3.0, installation speed 70MB/S in awoo, maybe i'm wrong, you can check it out, thanks for the guide, i didn't quite understand it yet.

This is hos version 14.0.0 -

PATCH magic：50  41  54  43  48
Offset： 00  76  34
Size of patch：00  08
Patch to be applied：20  00  80  52  C0  03  5F  D6  
EOF magic： 45  4F  46

Sorry, I don't quite understand.

**Comment by borntohonk** [comment]
> can you add usb3.0 patch? ams since hos13, usb3.0 is not working, i found that by patching i can turn on usb3.0, installation speed 70MB/S in awoo, maybe i'm wrong, you can check it out, thanks for the guide, i didn't quite understand it yet.
> 
> This is hos version 14.0.0 -
> 
> PATCH magic：50 41 54 43 48 Offset： 00 76 34 Size of patch：00 08 Patch to be applied：20 00 80 52 C0 03 5F D6 EOF magic： 45 4F 46
> 
> Sorry, I don't quite understand.

https://github.com/Atmosphere-NX/Atmosphere/blob/master/fusee/program/source/fusee_setup_horizon.cpp#L571-L590
https://github.com/Atmosphere-NX/Atmosphere/blob/master/stratosphere/ams_mitm/source/set_mitm/settings_sd_kvs.cpp#L312-L315
https://github.com/Atmosphere-NX/Atmosphere/blob/master/stratosphere/loader/source/ldr_patcher.cpp#L125-L142
https://github.com/Atmosphere-NX/Atmosphere/blob/master/stratosphere/loader/source/ldr_embedded_usb_patches.inc#L47-L55

**Comment by borntohonk** [comment]
Atmosphere already has code for this, no need for a separate patch.
the buildid for 14.x.x is 1C97AFF30D48AFFEB74B28A530D30ABA0ABB9FFF (according to atmosphere source code)

and the patch applied are (again, according to atmoshere source code, which includes usb 3 patches): 
offset 007414; size 00 08, patch 20 00 80 52 c0 03 5f d6
offset 0074A4; size 00 08, patch 20 00 80 52 c0 03 5f d6

**Comment by borntohonk** [comment]
> Thank you very much, 1C97AFF30D48AFFEB74B28A530D30ABA0ABB9FFF.ips took effect, however, need to enable usb30_force_enabled = u8!0x1 in system_settings.ini, thank you very much for the guide, thanks!

Well you don't need 1C97AFF30D48AFFEB74B28A530D30ABA0ABB9FFF.ips, all you need to do is enable it in system_settings.ini and place it in the atmosphere config folder.

**Comment by lsp199308** [comment]
If I just enable it in system_settings.ini and put it into config, it won't work and awoo installs at 40MB/S. Putting 1C97AFF30D48AFFEB74B28A530D30ABA0ABB9FFF.ips into atmosphere/esefs_ patches/, the installation speed of awoo is 70MB/S.

**Comment by borntohonk** [comment]
> If I just enable it in system_settings.ini and put it into config, it won't work and awoo installs at 40MB/S. Putting 1C97AFF30D48AFFEB74B28A530D30ABA0ABB9FFF.ips into atmosphere/esefs_ patches/, the installation speed of awoo is 70MB/S.

I will consider generating them and distributing them if that is the case, if anything that sounds like an atmosphere bug

**Comment by borntohonk** [comment]
@lsp199308 https://github.com/borntohonk/SigPatches/commit/84e276a13152f2cc81ef3bc89b5b2059bc556c65

After reviewing the patches for 14.0.0, I came to notice that atmospheres 14.0.0 patches do not account for the 0x100 header that all other exefs ips patches account for, so 

"50 41 54 43 48 00 74 14 00 08 20 00 80 52 C0 03 5F D6 00 74 A4 00 08 20 00 80 52 C0 03 5F D6 45 4F 46"
should be
"50 41 54 43 48 00 75 14 00 08 20 00 80 52 C0 03 5F D6 00 75 A4 00 08 20 00 80 52 C0 03 5F D6 45 4F 46"

usb build-id: 1C97AFF30D48AFFEB74B28A530D30ABA0ABB9FFF
usb offset and patch at: 007514000820008052C0035FD6 and 0075A4000820008052C0035FD6

could you verify that the new one gives you the correct speed?

**Comment by borntohonk** [comment]
@lsp199308 from what i can tell this patch should not fix usb 3 speed, as the patch must be applied earlier, which is what system_settings.ini is for

**Comment by lsp199308** [comment]
@borntohonk I'm very sorry, I may be wrong, was able to enable usb3 in ams1.3.2, I tested it this morning with the latest version of ams, only to find out that it is possible to enable usb3, I haven't upgraded ams,ams1.3.1 usb3 doesn't work. Sorry.

However, I hope you can keep the usb3 patch, thanks, very sorry

**Comment by borntohonk** [comment]
> @borntohonk I'm very sorry, I may be wrong, was able to enable usb3 in ams1.3.2, I tested it this morning with the latest version of ams, only to find out that it is possible to enable usb3, I haven't upgraded ams,ams1.3.1 usb3 doesn't work. Sorry.
> 
> However, I hope you can keep the usb3 patch, thanks, very sorry

Yeah, I already added a patch generator for it, but from what I can tell, it's not needed, so I will not distribute the patches by default.
