### ISSUE TITLE
hard mode will make hekate5.8.0 frozen when hekate frontpage right site emuNAND is pressed+using v4 hwfly OLED chip

### ISSUE THREAD

**Issue by johnkelvinliu** [borntohonk/SigPatches#6]
After getting in atmosphere first time, going back to hekate5.8.0,
modifying the .ini by hard mode will make hekate5.8.0 frozen when the hekate frontpage right site's emuNAND is pressed+using v4 hwfly OLED chip with 0.7.0 hwfly nx.

EZ mode no problem. 
Soft modding switch no problem.

**Comment by borntohonk** [comment]
> johnkelvinliu

This repository does not include any hekate configs, are you sure you're submitting this issue to the correct repository?

The generated 'patches.ini' ( https://github.com/borntohonk/SigPatches/blob/master/hekate_patches/patches.ini ) is not a config file, nor is it loaded without a proper hekate config file.

**Comment by borntohonk** [comment]
@johnkelvinliu I'm also assuming you mean hekate version 5.8.0, not 3.8.0, as 5.8.0 is the latest. ( https://github.com/CTCaer/hekate/releases/tag/v5.8.0 )
